{"name": "Проверка невозможности создания Пользователя с ранее зарегестрированными данными", "status": "passed", "steps": [{"name": "Проверка невозможности создания Пользователя с дублирующими данными (код - 403 и текст \"message\": \"User already exists\" в ответе)", "status": "passed", "parameters": [{"name": "create_new_user", "value": "({'email': 'vunwzep@yandex.ru', 'password': 'qhgnbhpbrz', 'name': 'zinvhxngpw'}, <Response [200]>)"}], "start": 1730066263759, "stop": 1730066263896}], "start": 1730066263758, "stop": 1730066263897, "uuid": "4eb919dc-0092-42be-b032-24cdbc2e6f88", "historyId": "283739dca4831ee62d1289d70d3dffc5", "testCaseId": "283739dca4831ee62d1289d70d3dffc5", "fullName": "tests.test_create_user.TestCreateUser#test_create_user_doub_data_error", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_create_user"}, {"name": "subSuite", "value": "TestCreateUser"}, {"name": "host", "value": "DESKTOP-J7NC26E"}, {"name": "thread", "value": "15556-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_create_user"}]}